### ISSUE TITLE
cargo pgo optimize: Invalid cross-device link (os error 18)

### ISSUE THREAD

**Issue by burjui** [Kobzol/cargo-pgo#16]
I get this error when I run `cargo pgo optimize` on a project under `/home`, which is mounted on a separate partition. If I copy the project to e.g. `/tmp` and run the command on the copy - no problem whatsoever.

**Comment by Kobzol** [comment]
Heh, I was wondering whether this error could happen.. it seems that it indeed can happen :) I think that this is probably caused by the usage of `std::fs::rename` in `pgo optimize`. Sadly the `std::io::ErrorKind::CrossesDevices` error kind is still unstable, so I cannot detect this error easily, but I will change the code to just perform a copy if a move fails.

Could you please check if https://github.com/Kobzol/cargo-pgo/pull/17 fixes your problem?
```bash
$ cargo install --git https://github.com/kobzol/cargo-pgo --branch move-across-devices
```

**Comment by burjui** [comment]
Yes, the problem is gone, thank you :)

**Comment by QuarticCat** [comment]
I met this error as well. I was building https://github.com/Wilfred/difftastic through these commands:

```console
$ cargo pgo run -- sample_files/slow_before.rs sample_files/slow_after.rs
$ cargo pgo optimize run -- sample_files/slow_before.rs sample_files/slow_after.rs
```

My project is put in home dir. `/tmp` of my computer is tmpfs, while `/home` is btrfs.

**Comment by Kobzol** [comment]
I did not release a new version with the fix yet, I will do it soon.

Does it work for you with
```rust
$ cargo install --git https://github.com/kobzol/cargo-pgo --branch main
```
?

**Comment by QuarticCat** [comment]
It works perfectly. Thanks!
