### ISSUE TITLE
Support cargo namespaced features

### ISSUE THREAD

**Issue by r-ml** [Kobzol/cargo-pgo#2]
Bumping the cargo dependency should do the trick.

**Comment by Kobzol** [comment]
Hi! I wonder, is there a specific use-case that doesn't work for you with the current `cargo` version, e.g. you run `cargo pgo ...` and it fails because of the older dependency?

I have actually pinned the `cargo` dependency to an older version explicitly, since the newer one was causing some build problems on CI and it also required quite recent MSRV. But if there are problems with it I can try to bump it. Actually I would rather get rid of it completely, if there was an easy and robust way of finding the most basic workspace information..

**Comment by inflation** [comment]
Features like this:

```toml
image = ["dep:image"]
```

are available after cargo 1.60.

**Comment by Kobzol** [comment]
I know, but I was wondering how does this affect the users of this crate specifically. I tried it now and indeed such crates cannot be built with `cargo pgo`. I'll fix it.

**Comment by Kobzol** [comment]
Could you please check if it now works with the version from the linked PR? You can install it with this command:
```bash
$ cargo install --git https://github.com/kobzol/cargo-pgo --branch remove-cargo-dep
```

**Comment by inflation** [comment]
@Kobzol Yes, it works fine.

**Comment by r-ml** [comment]
It works, thanks!

**Comment by Kobzol** [comment]
Great :) I'll merge it then and release a new version soon.
